/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Restaurant.Item;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.InputMismatchException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.LoginPage.LoginPageJPanel;

/**
 *
 * @author swapn
 */
public class AdminManageMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminManageMenuJPanel
     */
    private JPanel container;
    private EcoSystem ecosystem;
    private DB4OUtil dB4OUtil;
    private UserAccount userAccount;

    public AdminManageMenuJPanel(JPanel container, UserAccount userAccount, EcoSystem ecosystem, DB4OUtil dB4OUtil) {
        initComponents();
        this.container = container;
        this.ecosystem = ecosystem;
        this.dB4OUtil = dB4OUtil;
        this.userAccount = userAccount;
        jPanelSummary.setVisible(false);
        populateMenuTable();
    }

    protected void paintComponent(Graphics g){
        Graphics2D g2d= (Graphics2D)g;
        int width=getWidth();
        int height= getHeight();
        
        Color color1= new Color(0, 105, 146);
        Color color2= new Color(162, 238, 242);
        GradientPaint gp = new GradientPaint(0,0,color1,0,height,color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, width, height);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        editItemButton = new javax.swing.JButton();
        logoutButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addItemButton = new javax.swing.JButton();
        removeItemButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelSummary = new javax.swing.JPanel();
        labelPassword = new javax.swing.JLabel();
        jLabeladdUpdateSummary = new javax.swing.JLabel();
        changeItemButton = new javax.swing.JButton();
        jTextFieldItemName = new javax.swing.JTextField();
        jTextFieldItemPrice = new javax.swing.JTextField();
        labelusername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton2.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        backButton2.setText("Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });
        add(backButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, -1));

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Item Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menuTable.setShowGrid(false);
        jScrollPane1.setViewportView(menuTable);
        if (menuTable.getColumnModel().getColumnCount() > 0) {
            menuTable.getColumnModel().getColumn(0).setMaxWidth(70);
            menuTable.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 113, 348, 92));

        editItemButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        editItemButton.setText("Edit Item");
        editItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editItemButtonActionPerformed(evt);
            }
        });
        add(editItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 217, 100, -1));

        logoutButton1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        logoutButton1.setText("Logout");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });
        add(logoutButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 6, 94, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Menu");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 68, 267, -1));

        addItemButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });
        add(addItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 217, 100, -1));

        removeItemButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        removeItemButton.setText("Remove Item");
        removeItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemButtonActionPerformed(evt);
            }
        });
        add(removeItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 217, 110, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, 372, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 64, 14, 390));

        jPanelSummary.setOpaque(false);

        labelPassword.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPassword.setText("Item Price:");

        jLabeladdUpdateSummary.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 15)); // NOI18N
        jLabeladdUpdateSummary.setText("Dummy Text");

        changeItemButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        changeItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeItemButtonActionPerformed(evt);
            }
        });

        jTextFieldItemName.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jTextFieldItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemNameActionPerformed(evt);
            }
        });

        jTextFieldItemPrice.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jTextFieldItemPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemPriceActionPerformed(evt);
            }
        });

        labelusername.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        labelusername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelusername.setText("Item Name:");

        javax.swing.GroupLayout jPanelSummaryLayout = new javax.swing.GroupLayout(jPanelSummary);
        jPanelSummary.setLayout(jPanelSummaryLayout);
        jPanelSummaryLayout.setHorizontalGroup(
            jPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelSummaryLayout.createSequentialGroup()
                            .addComponent(labelusername, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelSummaryLayout.createSequentialGroup()
                            .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldItemPrice)
                                .addGroup(jPanelSummaryLayout.createSequentialGroup()
                                    .addComponent(changeItemButton)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSummaryLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabeladdUpdateSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelSummaryLayout.setVerticalGroup(
            jPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeladdUpdateSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelusername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(jPanelSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 272, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/giphy Food_1.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 400, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButton2ActionPerformed

    private void editItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editItemButtonActionPerformed
        // TODO add your handling code here:

        Restaurant r = this.ecosystem.getRestaurantDirectory().findResttaurantByUserName(this.userAccount.getUsername());
        DefaultTableModel dtm = (DefaultTableModel) menuTable.getModel();
        int rowNumber = menuTable.getSelectedRow();
        if (rowNumber == -1) {
            JOptionPane.showMessageDialog(null, "Please select an item to edit.");
        } else {
            jPanelSummary.setVisible(true);
            jLabeladdUpdateSummary.setText("Update Item");
            changeItemButton.setText("Update");
            Item i = r.getItemList().findItemByName(dtm.getValueAt(menuTable.getSelectedRow(), 1).toString());
            jTextFieldItemName.setText(i.getItemName());
            jTextFieldItemPrice.setText(String.valueOf(i.getItemPrice()));
        }

    }//GEN-LAST:event_editItemButtonActionPerformed

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        LoginPageJPanel lpp= new LoginPageJPanel(container, ecosystem, dB4OUtil);
        container.add("LoginPageJPanel", lpp);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutButton1ActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        jPanelSummary.setVisible(true);
        jLabeladdUpdateSummary.setText("Add Item");
        changeItemButton.setText("Add");
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void removeItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemButtonActionPerformed
        // TODO add your handling code here:
        
        Restaurant r = this.ecosystem.getRestaurantDirectory().findResttaurantByUserName(this.userAccount.getUsername());
        DefaultTableModel dtm = (DefaultTableModel) menuTable.getModel();
        int rowNumber = menuTable.getSelectedRow();
        if (rowNumber == -1) {
            JOptionPane.showMessageDialog(null, "Please select an item to remove.");
        } else {
            r.getItemList().removeItem(dtm.getValueAt(menuTable.getSelectedRow(), 1).toString());
            JOptionPane.showMessageDialog(null, "Item Removed.");
            populateMenuTable();
        }
    }//GEN-LAST:event_removeItemButtonActionPerformed

    private void jTextFieldItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemNameActionPerformed

    private void jTextFieldItemPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemPriceActionPerformed

    private void changeItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeItemButtonActionPerformed
        // TODO add your handling code here:
        Restaurant r = this.ecosystem.getRestaurantDirectory().findResttaurantByUserName(userAccount.getUsername());
        if (changeItemButton.getText().equals("Add")) {
            Item i = r.getItemList().addNewItem();
            i.setItemName(jTextFieldItemName.getText());
            i.setItemPrice(Double.parseDouble(jTextFieldItemPrice.getText()));
            JOptionPane.showMessageDialog(null, jTextFieldItemName.getText() + " added to menu.");
            populateMenuTable();
        } else if (changeItemButton.getText().equals("Update")) {
            DefaultTableModel dtm = (DefaultTableModel) menuTable.getModel();
            Item i = r.getItemList().findItemByName(dtm.getValueAt(menuTable.getSelectedRow(), 1).toString());
            if(jTextFieldItemName.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Item name cannot be empty.");
            }
            else if(jTextFieldItemPrice.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Item price cannot be empty.");
            }
            else{
                i.setItemName(jTextFieldItemName.getText());
                try{
                    i.setItemPrice(Double.parseDouble(jTextFieldItemPrice.getText()));
                    JOptionPane.showMessageDialog(null, "Updated item in menu.");
                    populateMenuTable();
                }
                catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null, "Price has to be numeric value");
                }
                
            }
            
        }
    }//GEN-LAST:event_changeItemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton changeItemButton;
    private javax.swing.JButton editItemButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabeladdUpdateSummary;
    private javax.swing.JPanel jPanelSummary;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldItemName;
    private javax.swing.JTextField jTextFieldItemPrice;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelusername;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JTable menuTable;
    private javax.swing.JButton removeItemButton;
    // End of variables declaration//GEN-END:variables

    private void populateMenuTable() {

        DefaultTableModel dtm = (DefaultTableModel) menuTable.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            dtm.removeRow(i);
        }
        Object[] row = new Object[3];
        for (String s : this.ecosystem.getRestaurantDirectory().getRestDirectory().keySet()) {
            for (String i : this.ecosystem.getRestaurantDirectory().getRestDirectory().get(s).getItemList().getItemList().keySet()) {
                row[0] = this.ecosystem.getRestaurantDirectory().getRestDirectory().get(s).getItemList().getItemList().get(i).getItemId();
                row[1] = this.ecosystem.getRestaurantDirectory().getRestDirectory().get(s).getItemList().getItemList().get(i).getItemName();
                row[2] = this.ecosystem.getRestaurantDirectory().getRestDirectory().get(s).getItemList().getItemList().get(i).getItemPrice();
                dtm.addRow(row);
            }
        }

    }
}
