/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author swapn
 */
public class ManageRestaurantsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantsJPanel
     */
    private JPanel container;
    private EcoSystem ecosystem;
    private DB4OUtil dB4OUtil;

    public ManageRestaurantsJPanel(JPanel container, EcoSystem ecosystem, DB4OUtil dB4OUtil) {
        initComponents();
        this.container = container;
        this.ecosystem = ecosystem;
        this.dB4OUtil = dB4OUtil;
        labelPassword.setVisible(false);
        labelusername.setVisible(false);
        labelusername1.setVisible(false);
        labelPassword1.setVisible(false);
        jTextFieldRestName1.setVisible(false);
        jTextFieldPassword.setVisible(false);
        jTextFieldRestContact.setVisible(false);
        jTextFieldUserName.setVisible(false);
        addRestaurantButton1.setVisible(false);
        populateTable();
    }

    protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();

        Color color1 = new Color(0, 105, 146);
        Color color2 = new Color(162, 238, 242);
        GradientPaint gp = new GradientPaint(0, 0, color1, 0, height, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        logoutButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        restaurantListJTable = new javax.swing.JTable();
        removeRestaurantButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addRestaurantButton = new javax.swing.JButton();
        labelusername = new javax.swing.JLabel();
        jTextFieldRestName1 = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        jTextFieldRestContact = new javax.swing.JTextField();
        labelusername1 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        labelPassword1 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        addRestaurantButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Restaurants Panel");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 267, -1));

        logoutButton1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        logoutButton1.setText("Logout");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });
        add(logoutButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 94, 30));

        restaurantListJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant ID", "Restaurant Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        restaurantListJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaurantListJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(restaurantListJTable);
        if (restaurantListJTable.getColumnModel().getColumnCount() > 0) {
            restaurantListJTable.getColumnModel().getColumn(0).setResizable(false);
            restaurantListJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 337, 109));

        removeRestaurantButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        removeRestaurantButton.setText("Remove Restaurant");
        removeRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRestaurantButtonActionPerformed(evt);
            }
        });
        add(removeRestaurantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/77bd9523d3332fd28e3e0baf341a95b8_1.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 600, 500));

        addRestaurantButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        addRestaurantButton.setText("Add Restaurant");
        addRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRestaurantButtonActionPerformed(evt);
            }
        });
        add(addRestaurantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        labelusername.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        labelusername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelusername.setText("Restaurant Name:");
        add(labelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, 25));

        jTextFieldRestName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRestName1ActionPerformed(evt);
            }
        });
        add(jTextFieldRestName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 192, -1));

        labelPassword.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPassword.setText("Contact Number:");
        add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, 25));

        jTextFieldRestContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRestContactActionPerformed(evt);
            }
        });
        add(jTextFieldRestContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 192, -1));

        labelusername1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        labelusername1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelusername1.setText("User Name:");
        add(labelusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, 25));

        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });
        add(jTextFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 154, -1));

        labelPassword1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        labelPassword1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPassword1.setText("Password:");
        add(labelPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 120, 25));

        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });
        add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 154, -1));

        addRestaurantButton1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        addRestaurantButton1.setText("Add ");
        addRestaurantButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRestaurantButton1ActionPerformed(evt);
            }
        });
        add(addRestaurantButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButtonActionPerformed

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutButton1ActionPerformed

    private void restaurantListJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantListJTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_restaurantListJTableMouseClicked

    private void removeRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRestaurantButtonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) restaurantListJTable.getModel();
        int rowNumber = restaurantListJTable.getSelectedRow();
        if (rowNumber != -1) {
            int result = JOptionPane.showConfirmDialog(null, "Confirm?");
            if (result == JOptionPane.YES_OPTION) {
                this.ecosystem.getRestaurantDirectory().findResttaurantByName(dtm.getValueAt(rowNumber, 1).toString()).setRestAdmin(null);
                this.ecosystem.getRestaurantDirectory().removeRestaurant(dtm.getValueAt(rowNumber, 0).toString());
                dtm.removeRow(rowNumber);
                populateTable();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select delivery man to remove.");
        }
    }//GEN-LAST:event_removeRestaurantButtonActionPerformed

    private void addRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRestaurantButtonActionPerformed
        // TODO add your handling code here:
        
        labelPassword.setVisible(true);
        labelusername.setVisible(true);
        labelusername1.setVisible(true);
        labelPassword1.setVisible(true);
        jTextFieldRestName1.setVisible(true);
        jTextFieldPassword.setVisible(true);
        jTextFieldRestContact.setVisible(true);
        jTextFieldUserName.setVisible(true);
        addRestaurantButton1.setVisible(true);
        
    }//GEN-LAST:event_addRestaurantButtonActionPerformed

    private void jTextFieldRestName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRestName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRestName1ActionPerformed

    private void jTextFieldRestContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRestContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRestContactActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void addRestaurantButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRestaurantButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextFieldRestName1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Restaurant Name cannot be empty.");
        }else if(jTextFieldUserName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "User Name cannot be empty.");
        }else if(jTextFieldPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password cannot be empty.");
        }
        else if(this.ecosystem.getUserAccountDirectory().authenticateUser(jTextFieldUserName.getText(), jTextFieldPassword.getText())!=null){
            JOptionPane.showMessageDialog(null, "Username alreay taken.");
        }
        else{
            UserAccount userAccount = this.ecosystem.getUserAccountDirectory().createUserAccount(jTextFieldUserName.getText(), jTextFieldPassword.getText(), new AdminRole());
            Restaurant r = this.ecosystem.getRestaurantDirectory().newRestaurant(userAccount);
            r.setRestName(jTextFieldRestName1.getText());
            if(!jTextFieldRestContact.getText().isEmpty())
                r.setContactNo(jTextFieldRestContact.getText());
            JOptionPane.showMessageDialog(null, "Restaurant Added");
            labelPassword.setVisible(false);
            labelusername.setVisible(false);
            labelusername1.setVisible(false);
            labelPassword1.setVisible(false);
            jTextFieldRestName1.setVisible(false);
            jTextFieldPassword.setVisible(false);
            jTextFieldRestContact.setVisible(false);
            jTextFieldUserName.setVisible(false);
            addRestaurantButton1.setVisible(false);
            populateTable();
        }
        
        
    }//GEN-LAST:event_addRestaurantButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRestaurantButton;
    private javax.swing.JButton addRestaurantButton1;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldRestContact;
    private javax.swing.JTextField jTextFieldRestName1;
    private javax.swing.JTextField jTextFieldUserName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPassword1;
    private javax.swing.JLabel labelusername;
    private javax.swing.JLabel labelusername1;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JButton removeRestaurantButton;
    private javax.swing.JTable restaurantListJTable;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) restaurantListJTable.getModel();
        dtm.setRowCount(0);
        for (String s : this.ecosystem.getRestaurantDirectory().getRestDirectory().keySet()) {
            Object row[] = new Object[2];
            row[0] = this.ecosystem.getRestaurantDirectory().getRestDirectory().get(s).getRestId();
            row[1] = this.ecosystem.getRestaurantDirectory().getRestDirectory().get(s).getRestName();
            dtm.addRow(row);
        }
    }
}
